// Auto-generated by magia-api — do not edit

import type { Manifest, MagiaOperation, MagiaMutation, MagiaTanStackQuery, MagiaTanStackMutation } from 'magia-api'
import type * as petstoreTypes from '../node_modules/.magia/internals/petstore'

type FlatInput<T> = T extends { path?: infer P; query?: infer Q; body?: infer B }
  ? (P extends object ? P : {}) & (Q extends object ? Q : {}) & (B extends object ? B : {})
  : T

export const manifest: Manifest = {
  "petstore": {
    plugins: [{ name: "tanstackQuery" }],
    operations: {
      "addPet": {
        method: "POST",
        path: "/pet",
        params: {"body":"body"},
      },
      "updatePet": {
        method: "PUT",
        path: "/pet",
        params: {"body":"body"},
      },
      "findPetsByStatus": {
        method: "GET",
        path: "/pet/findByStatus",
        params: {"status":"query"},
      },
      "findPetsByTags": {
        method: "GET",
        path: "/pet/findByTags",
        params: {"tags":"query"},
      },
      "getPetById": {
        method: "GET",
        path: "/pet/{petId}",
        params: {"petId":"path"},
      },
      "updatePetWithForm": {
        method: "POST",
        path: "/pet/{petId}",
        params: {"petId":"path","name":"query","status":"query"},
      },
      "deletePet": {
        method: "DELETE",
        path: "/pet/{petId}",
        params: {"petId":"path"},
      },
      "uploadFile": {
        method: "POST",
        path: "/pet/{petId}/uploadImage",
        params: {"petId":"path","additionalMetadata":"query","body":"body"},
      },
      "getInventory": {
        method: "GET",
        path: "/store/inventory",
        params: {},
      },
      "placeOrder": {
        method: "POST",
        path: "/store/order",
        params: {"body":"body"},
      },
      "getOrderById": {
        method: "GET",
        path: "/store/order/{orderId}",
        params: {"orderId":"path"},
      },
      "deleteOrder": {
        method: "DELETE",
        path: "/store/order/{orderId}",
        params: {"orderId":"path"},
      },
      "createUser": {
        method: "POST",
        path: "/user",
        params: {"body":"body"},
      },
      "createUsersWithListInput": {
        method: "POST",
        path: "/user/createWithList",
        params: {"body":"body"},
      },
      "loginUser": {
        method: "GET",
        path: "/user/login",
        params: {"username":"query","password":"query"},
      },
      "logoutUser": {
        method: "GET",
        path: "/user/logout",
        params: {},
      },
      "getUserByName": {
        method: "GET",
        path: "/user/{username}",
        params: {"username":"path"},
      },
      "updateUser": {
        method: "PUT",
        path: "/user/{username}",
        params: {"username":"path","body":"body"},
      },
      "deleteUser": {
        method: "DELETE",
        path: "/user/{username}",
        params: {"username":"path"},
      },
    },
  },
}

declare module 'magia-api' {
  interface MagiaClient {
    petstore: {
      addPet: MagiaMutation<FlatInput<petstoreTypes.AddPetData>, petstoreTypes.AddPetResponse>
        & MagiaTanStackMutation<FlatInput<petstoreTypes.AddPetData>, petstoreTypes.AddPetResponse>
      updatePet: MagiaMutation<FlatInput<petstoreTypes.UpdatePetData>, petstoreTypes.UpdatePetResponse>
        & MagiaTanStackMutation<FlatInput<petstoreTypes.UpdatePetData>, petstoreTypes.UpdatePetResponse>
      findPetsByStatus: MagiaOperation<FlatInput<petstoreTypes.FindPetsByStatusData>, petstoreTypes.FindPetsByStatusResponse>
        & MagiaTanStackQuery<FlatInput<petstoreTypes.FindPetsByStatusData>, petstoreTypes.FindPetsByStatusResponse>
      findPetsByTags: MagiaOperation<FlatInput<petstoreTypes.FindPetsByTagsData>, petstoreTypes.FindPetsByTagsResponse>
        & MagiaTanStackQuery<FlatInput<petstoreTypes.FindPetsByTagsData>, petstoreTypes.FindPetsByTagsResponse>
      getPetById: MagiaOperation<FlatInput<petstoreTypes.GetPetByIdData>, petstoreTypes.GetPetByIdResponse>
        & MagiaTanStackQuery<FlatInput<petstoreTypes.GetPetByIdData>, petstoreTypes.GetPetByIdResponse>
      updatePetWithForm: MagiaMutation<FlatInput<petstoreTypes.UpdatePetWithFormData>, petstoreTypes.UpdatePetWithFormResponse>
        & MagiaTanStackMutation<FlatInput<petstoreTypes.UpdatePetWithFormData>, petstoreTypes.UpdatePetWithFormResponse>
      deletePet: MagiaMutation<FlatInput<petstoreTypes.DeletePetData>, void>
        & MagiaTanStackMutation<FlatInput<petstoreTypes.DeletePetData>, void>
      uploadFile: MagiaMutation<FlatInput<petstoreTypes.UploadFileData>, petstoreTypes.UploadFileResponse>
        & MagiaTanStackMutation<FlatInput<petstoreTypes.UploadFileData>, petstoreTypes.UploadFileResponse>
      getInventory: MagiaOperation<void, petstoreTypes.GetInventoryResponse>
        & MagiaTanStackQuery<void, petstoreTypes.GetInventoryResponse>
      placeOrder: MagiaMutation<FlatInput<petstoreTypes.PlaceOrderData>, petstoreTypes.PlaceOrderResponse>
        & MagiaTanStackMutation<FlatInput<petstoreTypes.PlaceOrderData>, petstoreTypes.PlaceOrderResponse>
      getOrderById: MagiaOperation<FlatInput<petstoreTypes.GetOrderByIdData>, petstoreTypes.GetOrderByIdResponse>
        & MagiaTanStackQuery<FlatInput<petstoreTypes.GetOrderByIdData>, petstoreTypes.GetOrderByIdResponse>
      deleteOrder: MagiaMutation<FlatInput<petstoreTypes.DeleteOrderData>, void>
        & MagiaTanStackMutation<FlatInput<petstoreTypes.DeleteOrderData>, void>
      createUser: MagiaMutation<FlatInput<petstoreTypes.CreateUserData>, petstoreTypes.CreateUserResponse>
        & MagiaTanStackMutation<FlatInput<petstoreTypes.CreateUserData>, petstoreTypes.CreateUserResponse>
      createUsersWithListInput: MagiaMutation<FlatInput<petstoreTypes.CreateUsersWithListInputData>, petstoreTypes.CreateUsersWithListInputResponse>
        & MagiaTanStackMutation<FlatInput<petstoreTypes.CreateUsersWithListInputData>, petstoreTypes.CreateUsersWithListInputResponse>
      loginUser: MagiaOperation<FlatInput<petstoreTypes.LoginUserData>, petstoreTypes.LoginUserResponse>
        & MagiaTanStackQuery<FlatInput<petstoreTypes.LoginUserData>, petstoreTypes.LoginUserResponse>
      logoutUser: MagiaOperation<void, void>
        & MagiaTanStackQuery<void, void>
      getUserByName: MagiaOperation<FlatInput<petstoreTypes.GetUserByNameData>, petstoreTypes.GetUserByNameResponse>
        & MagiaTanStackQuery<FlatInput<petstoreTypes.GetUserByNameData>, petstoreTypes.GetUserByNameResponse>
      updateUser: MagiaMutation<FlatInput<petstoreTypes.UpdateUserData>, void>
        & MagiaTanStackMutation<FlatInput<petstoreTypes.UpdateUserData>, void>
      deleteUser: MagiaMutation<FlatInput<petstoreTypes.DeleteUserData>, void>
        & MagiaTanStackMutation<FlatInput<petstoreTypes.DeleteUserData>, void>
      pathKey(): readonly ['magia', 'petstore']
    }
  }
}
