// Auto-generated by magia-api — do not edit

import type * as petstoreTypes from '../node_modules/.magia/internals/petstore'

declare module 'magia-api' {
  interface MagiaClient {
    petstore: {
      addPet: MagiaMutation<petstoreTypes.AddPetData, petstoreTypes.AddPetResponse>
        & MagiaTanStackMutation<petstoreTypes.AddPetData, petstoreTypes.AddPetResponse>
      updatePet: MagiaMutation<petstoreTypes.UpdatePetData, petstoreTypes.UpdatePetResponse>
        & MagiaTanStackMutation<petstoreTypes.UpdatePetData, petstoreTypes.UpdatePetResponse>
      findPetsByStatus: MagiaOperation<petstoreTypes.FindPetsByStatusData, petstoreTypes.FindPetsByStatusResponse>
        & MagiaTanStackQuery<petstoreTypes.FindPetsByStatusData, petstoreTypes.FindPetsByStatusResponse>
      findPetsByTags: MagiaOperation<petstoreTypes.FindPetsByTagsData, petstoreTypes.FindPetsByTagsResponse>
        & MagiaTanStackQuery<petstoreTypes.FindPetsByTagsData, petstoreTypes.FindPetsByTagsResponse>
      getPetById: MagiaOperation<petstoreTypes.GetPetByIdData, petstoreTypes.GetPetByIdResponse>
        & MagiaTanStackQuery<petstoreTypes.GetPetByIdData, petstoreTypes.GetPetByIdResponse>
      updatePetWithForm: MagiaMutation<petstoreTypes.UpdatePetWithFormData, petstoreTypes.UpdatePetWithFormResponse>
        & MagiaTanStackMutation<petstoreTypes.UpdatePetWithFormData, petstoreTypes.UpdatePetWithFormResponse>
      deletePet: MagiaMutation<petstoreTypes.DeletePetData, petstoreTypes.DeletePetResponse>
        & MagiaTanStackMutation<petstoreTypes.DeletePetData, petstoreTypes.DeletePetResponse>
      uploadFile: MagiaMutation<petstoreTypes.UploadFileData, petstoreTypes.UploadFileResponse>
        & MagiaTanStackMutation<petstoreTypes.UploadFileData, petstoreTypes.UploadFileResponse>
      getInventory: MagiaOperation<void, petstoreTypes.GetInventoryResponse>
        & MagiaTanStackQuery<void, petstoreTypes.GetInventoryResponse>
      placeOrder: MagiaMutation<petstoreTypes.PlaceOrderData, petstoreTypes.PlaceOrderResponse>
        & MagiaTanStackMutation<petstoreTypes.PlaceOrderData, petstoreTypes.PlaceOrderResponse>
      getOrderById: MagiaOperation<petstoreTypes.GetOrderByIdData, petstoreTypes.GetOrderByIdResponse>
        & MagiaTanStackQuery<petstoreTypes.GetOrderByIdData, petstoreTypes.GetOrderByIdResponse>
      deleteOrder: MagiaMutation<petstoreTypes.DeleteOrderData, petstoreTypes.DeleteOrderResponse>
        & MagiaTanStackMutation<petstoreTypes.DeleteOrderData, petstoreTypes.DeleteOrderResponse>
      createUser: MagiaMutation<petstoreTypes.CreateUserData, petstoreTypes.CreateUserResponse>
        & MagiaTanStackMutation<petstoreTypes.CreateUserData, petstoreTypes.CreateUserResponse>
      createUsersWithListInput: MagiaMutation<petstoreTypes.CreateUsersWithListInputData, petstoreTypes.CreateUsersWithListInputResponse>
        & MagiaTanStackMutation<petstoreTypes.CreateUsersWithListInputData, petstoreTypes.CreateUsersWithListInputResponse>
      loginUser: MagiaOperation<petstoreTypes.LoginUserData, petstoreTypes.LoginUserResponse>
        & MagiaTanStackQuery<petstoreTypes.LoginUserData, petstoreTypes.LoginUserResponse>
      logoutUser: MagiaOperation<void, petstoreTypes.LogoutUserResponse>
        & MagiaTanStackQuery<void, petstoreTypes.LogoutUserResponse>
      getUserByName: MagiaOperation<petstoreTypes.GetUserByNameData, petstoreTypes.GetUserByNameResponse>
        & MagiaTanStackQuery<petstoreTypes.GetUserByNameData, petstoreTypes.GetUserByNameResponse>
      updateUser: MagiaMutation<petstoreTypes.UpdateUserData, petstoreTypes.UpdateUserResponse>
        & MagiaTanStackMutation<petstoreTypes.UpdateUserData, petstoreTypes.UpdateUserResponse>
      deleteUser: MagiaMutation<petstoreTypes.DeleteUserData, petstoreTypes.DeleteUserResponse>
        & MagiaTanStackMutation<petstoreTypes.DeleteUserData, petstoreTypes.DeleteUserResponse>
      pathKey(): readonly ['magia', 'petstore']
    }
  }
}
