// Auto-generated by magia-api — do not edit
import type { Manifest } from 'magia-api'

export const manifest: Manifest = {
  "petstore": {
    plugins: [{ name: "tanstackQuery" }],
    operations: {
      "addPet": {
        method: "POST",
        path: "/pet",
        params: {"body":"body"},
      },
      "updatePet": {
        method: "PUT",
        path: "/pet",
        params: {"body":"body"},
      },
      "findPetsByStatus": {
        method: "GET",
        path: "/pet/findByStatus",
        params: {"status":"query"},
      },
      "findPetsByTags": {
        method: "GET",
        path: "/pet/findByTags",
        params: {"tags":"query"},
      },
      "getPetById": {
        method: "GET",
        path: "/pet/{petId}",
        params: {"petId":"path"},
      },
      "updatePetWithForm": {
        method: "POST",
        path: "/pet/{petId}",
        params: {"petId":"path","name":"query","status":"query"},
      },
      "deletePet": {
        method: "DELETE",
        path: "/pet/{petId}",
        params: {"petId":"path"},
      },
      "uploadFile": {
        method: "POST",
        path: "/pet/{petId}/uploadImage",
        params: {"petId":"path","additionalMetadata":"query","body":"body"},
      },
      "getInventory": {
        method: "GET",
        path: "/store/inventory",
        params: {},
      },
      "placeOrder": {
        method: "POST",
        path: "/store/order",
        params: {"body":"body"},
      },
      "getOrderById": {
        method: "GET",
        path: "/store/order/{orderId}",
        params: {"orderId":"path"},
      },
      "deleteOrder": {
        method: "DELETE",
        path: "/store/order/{orderId}",
        params: {"orderId":"path"},
      },
      "createUser": {
        method: "POST",
        path: "/user",
        params: {"body":"body"},
      },
      "createUsersWithListInput": {
        method: "POST",
        path: "/user/createWithList",
        params: {"body":"body"},
      },
      "loginUser": {
        method: "GET",
        path: "/user/login",
        params: {"username":"query","password":"query"},
      },
      "logoutUser": {
        method: "GET",
        path: "/user/logout",
        params: {},
      },
      "getUserByName": {
        method: "GET",
        path: "/user/{username}",
        params: {"username":"path"},
      },
      "updateUser": {
        method: "PUT",
        path: "/user/{username}",
        params: {"username":"path","body":"body"},
      },
      "deleteUser": {
        method: "DELETE",
        path: "/user/{username}",
        params: {"username":"path"},
      },
    },
  },
}
