/**
 * Hand-crafted type augmentation for the spike.
 * In production, this file is auto-generated by the codegen engine
 * and placed at src/magia-api.d.ts (gitignored).
 */

import type {
  MagiaOperation,
  MagiaMutation,
  MagiaTanStackQuery,
  MagiaTanStackMutation,
} from 'magia-api'

// -- Petstore types (hand-crafted from OpenAPI spec) --

interface Pet {
  id: number
  name: string
  status: 'available' | 'pending' | 'sold'
  photoUrls: string[]
  category?: { id: number; name: string }
  tags?: { id: number; name: string }[]
}

interface GetPetByIdParams {
  petId: number
}

interface ListPetsParams {
  status?: 'available' | 'pending' | 'sold'
}

interface CreatePetParams {
  name: string
  status?: 'available' | 'pending' | 'sold'
  photoUrls?: string[]
}

interface UpdatePetParams {
  id: number
  name: string
  status?: 'available' | 'pending' | 'sold'
}

interface DeletePetParams {
  petId: number
}

// -- Module augmentation --

declare module 'magia-api' {
  interface MagiaClient {
    petstore: {
      getPetById: MagiaOperation<GetPetByIdParams, Pet>
        & MagiaTanStackQuery<GetPetByIdParams, Pet>
      listPets: MagiaOperation<ListPetsParams, Pet[]>
        & MagiaTanStackQuery<ListPetsParams, Pet[]>
      createPet: MagiaMutation<CreatePetParams, Pet>
        & MagiaTanStackMutation<CreatePetParams, Pet>
      updatePet: MagiaMutation<UpdatePetParams, Pet>
        & MagiaTanStackMutation<UpdatePetParams, Pet>
      deletePet: MagiaMutation<DeletePetParams, void>
        & MagiaTanStackMutation<DeletePetParams, void>
      findPetsByStatus: MagiaOperation<ListPetsParams, Pet[]>
        & MagiaTanStackQuery<ListPetsParams, Pet[]>
      pathKey(): readonly ['magia', 'petstore']
    }
  }
}
