import type { ExtractedOperation } from './extractor'
import type { MagiaPlugin } from '../types'
import type { OpenApiSpec, OpenApiOperation, OpenApiPathItem } from './parser'

const HTTP_METHODS = ['get', 'post', 'put', 'delete', 'patch'] as const

interface DtsApiInfo {
  operations: ExtractedOperation[]
  plugins: MagiaPlugin[]
  typesImportPath: string // relative path to Hey API generated types
  spec: OpenApiSpec
}

/**
 * Check if an operation is a mutation (non-GET).
 */
function isMutation(method: string): boolean {
  return method !== 'GET'
}

/**
 * Check if plugins include tanstackQuery.
 */
function hasTanStackQuery(plugins: MagiaPlugin[]): boolean {
  return plugins.some(p => p.name === 'tanstackQuery')
}

/**
 * Look up the OpenAPI operation object to find response type name.
 */
function findOperation(spec: OpenApiSpec, method: string, path: string): OpenApiOperation | null {
  const pathItem = spec.paths?.[path]
  if (!pathItem) return null
  return (pathItem as Record<string, OpenApiOperation>)[method.toLowerCase()] ?? null
}

/**
 * Resolve the response type name from Hey API's generated types.
 * Hey API names response types as `<OperationId>Response`.
 */
function getResponseTypeName(operationId: string): string {
  // Hey API capitalizes the first letter
  const capitalized = operationId[0].toUpperCase() + operationId.slice(1)
  return `${capitalized}Response`
}

/**
 * Resolve the request/input type name.
 * Hey API names them as `<OperationId>Data`.
 */
function getRequestTypeName(operationId: string): string {
  const capitalized = operationId[0].toUpperCase() + operationId.slice(1)
  return `${capitalized}Data`
}

/**
 * Generate the magia-api.d.ts type augmentation source.
 */
export function generateDts(
  apis: Record<string, DtsApiInfo>,
): string {
  const lines: string[] = []

  lines.push(`// Auto-generated by magia-api — do not edit`)
  lines.push(``)

  // Import Hey API generated types per API
  for (const [apiName, api] of Object.entries(apis)) {
    lines.push(`import type * as ${apiName}Types from '${api.typesImportPath}'`)
  }
  lines.push(``)

  lines.push(`declare module 'magia-api' {`)
  lines.push(`  interface MagiaClient {`)

  for (const [apiName, api] of Object.entries(apis)) {
    lines.push(`    ${apiName}: {`)

    const tq = hasTanStackQuery(api.plugins)

    for (const op of api.operations) {
      const mutation = isMutation(op.entry.method)
      const reqType = `${apiName}Types.${getRequestTypeName(op.operationName)}`
      const resType = `${apiName}Types.${getResponseTypeName(op.operationName)}`

      // Check if this operation has parameters/body (needs input type)
      const hasParams = Object.keys(op.entry.params).length > 0
      const inputType = hasParams ? reqType : 'void'

      if (mutation) {
        let typeLine = `      ${op.operationName}: MagiaMutation<${inputType}, ${resType}>`
        if (tq) {
          typeLine += `\n        & MagiaTanStackMutation<${inputType}, ${resType}>`
        }
        lines.push(typeLine)
      } else {
        let typeLine = `      ${op.operationName}: MagiaOperation<${inputType}, ${resType}>`
        if (tq) {
          typeLine += `\n        & MagiaTanStackQuery<${inputType}, ${resType}>`
        }
        lines.push(typeLine)
      }
    }

    // pathKey
    lines.push(`      pathKey(): readonly ['magia', '${apiName}']`)
    lines.push(`    }`)
  }

  lines.push(`  }`)
  lines.push(`}`)
  lines.push(``)

  return lines.join('\n')
}
