import type { ExtractedOperation } from "./extractor";
import type { GraphQLExtractedOperation } from "./graphql-codegen";
import type { MagiaPlugin } from "../types";

interface GenApiInfoBase {
  plugins: MagiaPlugin[];
  typesImportPath: string;
  exportedTypes: Set<string>;
}

interface GenRestApiInfo extends GenApiInfoBase {
  apiType: "rest";
  operations: ExtractedOperation[];
}

interface GenGraphQLApiInfo extends GenApiInfoBase {
  apiType: "graphql";
  operations: GraphQLExtractedOperation[];
}

type GenApiInfo = GenRestApiInfo | GenGraphQLApiInfo;

function hasTanStackQuery(plugins: MagiaPlugin[]): boolean {
  return plugins.some((p) => p.name === "tanstackQuery");
}

function capitalize(s: string): string {
  return s[0].toUpperCase() + s.slice(1);
}

/**
 * Generate the single magia.gen.ts file.
 * Contains both the runtime manifest and the module augmentation types.
 */
export function generateGenFile(apis: Record<string, GenApiInfo>): string {
  const lines: string[] = [];

  lines.push(`// Auto-generated by magia-api — do not edit`);
  lines.push(``);

  // Imports — only include TQ types if any API uses it
  const anyTq = Object.values(apis).some((a) => hasTanStackQuery(a.plugins));
  const coreTypes = ["Manifest", "ManifestApi", "MagiaOperation", "MagiaMutation", "MagiaError"];
  if (anyTq) coreTypes.push("MagiaTanStackQuery", "MagiaTanStackMutation");
  lines.push(`import type { ${coreTypes.join(", ")} } from 'magia-api'`);
  for (const [apiName, api] of Object.entries(apis)) {
    lines.push(`import type * as ${apiName}Types from '${api.typesImportPath}'`);
  }
  lines.push(``);

  // Helper: flatten Hey API's { path, query, headers, body } into flat params (REST only)
  const hasRest = Object.values(apis).some((a) => a.apiType === "rest");
  if (hasRest) {
    lines.push(
      `type FlatInput<T> = T extends { path?: infer P; query?: infer Q; headers?: infer H; body?: infer B }`,
    );
    lines.push(
      `  ? (P extends object ? P : {}) & (Q extends object ? Q : {}) & (H extends object ? H : {}) & (B extends object ? B : {})`,
    );
    lines.push(`  : T`);
    lines.push(``);
  }

  // ── Runtime: per-API manifests (tree-shakeable) ──
  const apiNames = Object.keys(apis);
  for (const [apiName, api] of Object.entries(apis)) {
    const pluginsList = api.plugins.map((p) => `{ name: ${JSON.stringify(p.name)} }`).join(", ");
    lines.push(`export const ${apiName}Manifest: ManifestApi = {`);
    lines.push(`  plugins: [${pluginsList}],`);
    lines.push(`  operations: {`);

    if (api.apiType === "rest") {
      for (const op of api.operations) {
        lines.push(`    ${JSON.stringify(op.operationName)}: {`);
        lines.push(`      type: "rest",`);
        lines.push(`      method: ${JSON.stringify(op.entry.method)},`);
        lines.push(`      path: ${JSON.stringify(op.entry.path)},`);
        lines.push(`      params: ${JSON.stringify(op.entry.params)},`);
        lines.push(`    },`);
      }
    } else {
      for (const op of api.operations) {
        lines.push(`    ${JSON.stringify(op.operationName)}: {`);
        lines.push(`      type: "graphql",`);
        lines.push(`      kind: ${JSON.stringify(op.kind)},`);
        lines.push(`      document: ${JSON.stringify(op.document)},`);
        lines.push(`    },`);
      }
    }

    lines.push(`  },`);
    lines.push(`}`);
    lines.push(``);
  }

  // ── Runtime: full manifest (composed from per-API) ──
  lines.push(`export const manifest: Manifest = {`);
  for (const apiName of apiNames) {
    lines.push(`  ${JSON.stringify(apiName)}: ${apiName}Manifest,`);
  }
  lines.push(`}`);
  lines.push(``);

  // ── Types: module augmentation ──
  lines.push(`declare module 'magia-api' {`);
  lines.push(`  interface MagiaClient {`);

  for (const [apiName, api] of Object.entries(apis)) {
    lines.push(`    ${apiName}: {`);

    const tq = hasTanStackQuery(api.plugins);
    const ns = `${apiName}Types`;

    if (api.apiType === "rest") {
      emitRestTypes(lines, api, ns, tq);
    } else {
      emitGraphQLTypes(lines, api, ns, tq);
    }

    lines.push(`      pathKey(): readonly ['magia', '${apiName}']`);
    lines.push(`    }`);
  }

  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);

  return lines.join("\n");
}

function emitRestTypes(lines: string[], api: GenRestApiInfo, ns: string, tq: boolean): void {
  for (const op of api.operations) {
    const isMut = op.entry.method !== "GET";
    const hasParams = Object.keys(op.entry.params).length > 0;
    const capName = capitalize(op.operationName);

    const dataTypeName = `${capName}Data`;
    const responseTypeName = `${capName}Response`;
    const errorsTypeName = `${capName}Errors`;
    const hasDataType = api.exportedTypes.has(dataTypeName);
    const hasResponseType = api.exportedTypes.has(responseTypeName);
    const hasErrorsType = api.exportedTypes.has(errorsTypeName);

    const reqType = hasParams && hasDataType ? `FlatInput<${ns}.${dataTypeName}>` : "void";
    const resType = hasResponseType ? `${ns}.${responseTypeName}` : "void";
    const errType = hasErrorsType ? `${ns}.${errorsTypeName}` : "{}";

    if (isMut) {
      let line = `      ${op.operationName}: MagiaMutation<${reqType}, ${resType}, ${errType}>`;
      if (tq) line += `\n        & MagiaTanStackMutation<${reqType}, ${resType}>`;
      lines.push(line);
    } else {
      let line = `      ${op.operationName}: MagiaOperation<${reqType}, ${resType}, ${errType}>`;
      if (tq) line += `\n        & MagiaTanStackQuery<${reqType}, ${resType}>`;
      lines.push(line);
    }
  }
}

function emitGraphQLTypes(lines: string[], api: GenGraphQLApiInfo, ns: string, tq: boolean): void {
  for (const op of api.operations) {
    const isMut = op.kind === "mutation";
    const capName = capitalize(op.operationName);

    // graphql-codegen generates: GetUserQuery, GetUserQueryVariables
    const queryTypeName = `${capName}Query`;
    const mutationTypeName = `${capName}Mutation`;
    const subscriptionTypeName = `${capName}Subscription`;
    const variablesTypeName = `${capName}QueryVariables`;
    const mutVarsTypeName = `${capName}MutationVariables`;
    const subVarsTypeName = `${capName}SubscriptionVariables`;

    let resType: string;
    let reqType: string;

    if (op.kind === "query") {
      resType = api.exportedTypes.has(queryTypeName) ? `${ns}.${queryTypeName}` : "unknown";
      reqType = api.exportedTypes.has(variablesTypeName) ? `${ns}.${variablesTypeName}` : "void";
    } else if (op.kind === "mutation") {
      resType = api.exportedTypes.has(mutationTypeName) ? `${ns}.${mutationTypeName}` : "unknown";
      reqType = api.exportedTypes.has(mutVarsTypeName) ? `${ns}.${mutVarsTypeName}` : "void";
    } else {
      resType = api.exportedTypes.has(subscriptionTypeName)
        ? `${ns}.${subscriptionTypeName}`
        : "unknown";
      reqType = api.exportedTypes.has(subVarsTypeName) ? `${ns}.${subVarsTypeName}` : "void";
    }

    if (isMut) {
      let line = `      ${op.operationName}: MagiaMutation<${reqType}, ${resType}>`;
      if (tq) line += `\n        & MagiaTanStackMutation<${reqType}, ${resType}>`;
      lines.push(line);
    } else {
      let line = `      ${op.operationName}: MagiaOperation<${reqType}, ${resType}>`;
      if (tq) line += `\n        & MagiaTanStackQuery<${reqType}, ${resType}>`;
      lines.push(line);
    }
  }
}
