import type { ExtractedOperation } from './extractor'
import type { MagiaPlugin } from '../types'

interface GenApiInfo {
  operations: ExtractedOperation[]
  plugins: MagiaPlugin[]
  typesImportPath: string
  exportedTypes: Set<string>
}

function isMutation(method: string): boolean {
  return method !== 'GET'
}

function hasTanStackQuery(plugins: MagiaPlugin[]): boolean {
  return plugins.some(p => p.name === 'tanstackQuery')
}

function capitalize(s: string): string {
  return s[0].toUpperCase() + s.slice(1)
}

/**
 * Generate the single magia.gen.ts file.
 * Contains both the runtime manifest and the module augmentation types.
 */
export function generateGenFile(
  apis: Record<string, GenApiInfo>,
): string {
  const lines: string[] = []

  lines.push(`// Auto-generated by magia-api — do not edit`)
  lines.push(``)

  // Imports — only include TQ types if any API uses it
  const anyTq = Object.values(apis).some(a => hasTanStackQuery(a.plugins))
  const coreTypes = ['Manifest', 'MagiaOperation', 'MagiaMutation']
  if (anyTq) coreTypes.push('MagiaTanStackQuery', 'MagiaTanStackMutation')
  lines.push(`import type { ${coreTypes.join(', ')} } from 'magia-api'`)
  for (const [apiName, api] of Object.entries(apis)) {
    lines.push(`import type * as ${apiName}Types from '${api.typesImportPath}'`)
  }
  lines.push(``)

  // Helper: flatten Hey API's { path, query, body } into flat params
  lines.push(`type FlatInput<T> = T extends { path?: infer P; query?: infer Q; body?: infer B }`)
  lines.push(`  ? (P extends object ? P : {}) & (Q extends object ? Q : {}) & (B extends object ? B : {})`)
  lines.push(`  : T`)
  lines.push(``)

  // ── Runtime: manifest ──
  lines.push(`export const manifest: Manifest = {`)
  for (const [apiName, api] of Object.entries(apis)) {
    lines.push(`  ${JSON.stringify(apiName)}: {`)

    const pluginsList = api.plugins.map(p => `{ name: ${JSON.stringify(p.name)} }`).join(', ')
    lines.push(`    plugins: [${pluginsList}],`)

    lines.push(`    operations: {`)
    for (const op of api.operations) {
      lines.push(`      ${JSON.stringify(op.operationName)}: {`)
      lines.push(`        method: ${JSON.stringify(op.entry.method)},`)
      lines.push(`        path: ${JSON.stringify(op.entry.path)},`)
      lines.push(`        params: ${JSON.stringify(op.entry.params)},`)
      lines.push(`      },`)
    }
    lines.push(`    },`)
    lines.push(`  },`)
  }
  lines.push(`}`)
  lines.push(``)

  // ── Types: module augmentation ──
  lines.push(`declare module 'magia-api' {`)
  lines.push(`  interface MagiaClient {`)

  for (const [apiName, api] of Object.entries(apis)) {
    lines.push(`    ${apiName}: {`)

    const tq = hasTanStackQuery(api.plugins)
    const ns = `${apiName}Types`

    for (const op of api.operations) {
      const mutation = isMutation(op.entry.method)
      const hasParams = Object.keys(op.entry.params).length > 0
      const capName = capitalize(op.operationName)

      // Check if Hey API actually exported these types
      const dataTypeName = `${capName}Data`
      const responseTypeName = `${capName}Response`
      const hasDataType = api.exportedTypes.has(dataTypeName)
      const hasResponseType = api.exportedTypes.has(responseTypeName)

      const reqType = hasParams && hasDataType ? `FlatInput<${ns}.${dataTypeName}>` : 'void'
      const resType = hasResponseType ? `${ns}.${responseTypeName}` : 'void'

      if (mutation) {
        let line = `      ${op.operationName}: MagiaMutation<${reqType}, ${resType}>`
        if (tq) line += `\n        & MagiaTanStackMutation<${reqType}, ${resType}>`
        lines.push(line)
      } else {
        let line = `      ${op.operationName}: MagiaOperation<${reqType}, ${resType}>`
        if (tq) line += `\n        & MagiaTanStackQuery<${reqType}, ${resType}>`
        lines.push(line)
      }
    }

    lines.push(`      pathKey(): readonly ['magia', '${apiName}']`)
    lines.push(`    }`)
  }

  lines.push(`  }`)
  lines.push(`}`)
  lines.push(``)

  return lines.join('\n')
}
