import type { ExtractedOperation } from "./extractor";
import type { GraphQLExtractedOperation } from "./graphql-codegen";
import type { MagiaPlugin } from "../types";

interface GenApiInfoBase {
  plugins: MagiaPlugin[];
  typesImportPath: string;
  exportedTypes: Set<string>;
}

interface GenRestApiInfo extends GenApiInfoBase {
  apiType: "rest";
  operations: ExtractedOperation[];
}

interface GenGraphQLApiInfo extends GenApiInfoBase {
  apiType: "graphql";
  operations: GraphQLExtractedOperation[];
}

type GenApiInfo = GenRestApiInfo | GenGraphQLApiInfo;

function hasTanStackQuery(plugins: MagiaPlugin[]): boolean {
  return plugins.some((p) => p.name === "tanstackQuery");
}

function capitalize(s: string): string {
  return s[0].toUpperCase() + s.slice(1);
}

/**
 * Generate the single magia.gen.ts file.
 * Contains both the runtime manifest and the module augmentation types.
 */
export function generateGenFile(apis: Record<string, GenApiInfo>): string {
  const lines: string[] = [];

  lines.push(`// Auto-generated by magia-api — do not edit`);
  lines.push(``);

  // Imports — only include TQ types if any API uses it
  const anyTq = Object.values(apis).some((a) => hasTanStackQuery(a.plugins));
  const anySSE = Object.values(apis).some((a) =>
    a.apiType === "rest"
      ? a.operations.some((op) => op.entry.sse)
      : a.operations.some((op) => op.kind === "subscription"),
  );
  const anyInfinite = Object.values(apis).some((a) =>
    a.operations.some((op) => ("entry" in op ? op.entry.pagination : op.pagination)),
  );
  const coreTypes = ["Manifest", "ManifestApi", "MagiaOperation", "MagiaMutation", "MagiaError"];
  if (anySSE) coreTypes.push("MagiaSSEOperation");
  if (anyTq) coreTypes.push("MagiaTanStackQuery", "MagiaTanStackMutation");
  if (anyTq && anyInfinite) coreTypes.push("MagiaTanStackInfiniteQuery");
  lines.push(`import type { ${coreTypes.join(", ")} } from 'magia-api'`);
  for (const [apiName, api] of Object.entries(apis)) {
    lines.push(`import type * as ${apiName}Types from '${api.typesImportPath}'`);
  }
  lines.push(``);

  // Helper: extract input type from openapi-typescript operations interface
  // Flattens path + query + header params + requestBody into a single type
  const hasRest = Object.values(apis).some((a) => a.apiType === "rest");
  if (hasRest) {
    lines.push(`// Flatten openapi-typescript operation params into a single input type`);
    lines.push(`type FlatInput<T> = T extends {`);
    lines.push(`  parameters?: { path?: infer P; query?: infer Q; header?: infer H };`);
    lines.push(`  requestBody?: { content: { [k: string]: infer B } };`);
    lines.push(`}`);
    lines.push(
      `  ? (P extends object ? P : {}) & (Q extends object ? Q : {}) & (H extends object ? H : {}) & (B extends object ? B : {})`,
    );
    lines.push(`  : T extends {`);
    lines.push(`    parameters?: { path?: infer P; query?: infer Q; header?: infer H };`);
    lines.push(`  }`);
    lines.push(
      `  ? (P extends object ? P : {}) & (Q extends object ? Q : {}) & (H extends object ? H : {})`,
    );
    lines.push(`  : {}`);
    lines.push(``);
    lines.push(`// Extract success response type (first 2XX response with application/json)`);
    lines.push(
      `type SuccessResponse<T> = T extends { 200: { content: { "application/json": infer R } } } ? R`,
    );
    lines.push(`  : T extends { 201: { content: { "application/json": infer R } } } ? R`);
    lines.push(`  : T extends { 204: { content: { "application/json": infer R } } } ? R`);
    lines.push(`  : void`);
    lines.push(``);
    lines.push(`// Extract error response types as { status: ErrorType } map`);
    lines.push(`type ErrorResponses<T> = {`);
    lines.push(`  [K in keyof T as K extends \`4\${string}\` | \`5\${string}\` ? K : never]:`);
    lines.push(`    T[K] extends { content: { "application/json": infer E } } ? E : unknown`);
    lines.push(`}`);
    lines.push(``);
  }

  // ── Runtime: per-API manifests (tree-shakeable) ──
  const apiNames = Object.keys(apis);
  for (const [apiName, api] of Object.entries(apis)) {
    const pluginsList = api.plugins.map((p) => `{ name: ${JSON.stringify(p.name)} }`).join(", ");
    lines.push(`export const ${apiName}Manifest: ManifestApi = {`);
    lines.push(`  plugins: [${pluginsList}],`);
    lines.push(`  operations: {`);

    if (api.apiType === "rest") {
      for (const op of api.operations) {
        lines.push(`    ${JSON.stringify(op.operationName)}: {`);
        lines.push(`      type: "rest",`);
        lines.push(`      method: ${JSON.stringify(op.entry.method)},`);
        lines.push(`      path: ${JSON.stringify(op.entry.path)},`);
        lines.push(`      params: ${JSON.stringify(op.entry.params)},`);
        if (op.entry.multipart) lines.push(`      multipart: true,`);
        if (op.entry.sse) lines.push(`      sse: true,`);
        if (op.entry.pagination)
          lines.push(`      pagination: ${JSON.stringify(op.entry.pagination)},`);
        lines.push(`    },`);
      }
    } else {
      for (const op of api.operations) {
        lines.push(`    ${JSON.stringify(op.operationName)}: {`);
        lines.push(`      type: "graphql",`);
        lines.push(`      kind: ${JSON.stringify(op.kind)},`);
        lines.push(`      document: ${JSON.stringify(op.document)},`);
        if (op.pagination) lines.push(`      pagination: ${JSON.stringify(op.pagination)},`);
        lines.push(`    },`);
      }
    }

    lines.push(`  },`);
    lines.push(`}`);
    lines.push(``);
  }

  // ── Runtime: full manifest (composed from per-API) ──
  lines.push(`export const manifest: Manifest = {`);
  for (const apiName of apiNames) {
    lines.push(`  ${JSON.stringify(apiName)}: ${apiName}Manifest,`);
  }
  lines.push(`}`);
  lines.push(``);

  // Lazy manifest for code splitting — each API loaded on first use
  if (apiNames.length > 1) {
    lines.push(`/** Lazy manifest — each API loaded on first use (for code splitting) */`);
    lines.push(`export const lazyManifest = {`);
    for (const apiName of apiNames) {
      lines.push(`  ${JSON.stringify(apiName)}: () => Promise.resolve(${apiName}Manifest),`);
    }
    lines.push(`}`);
    lines.push(``);
  }

  // ── Types: module augmentation ──
  lines.push(`declare module 'magia-api' {`);
  lines.push(`  interface MagiaClient {`);

  for (const [apiName, api] of Object.entries(apis)) {
    lines.push(`    ${apiName}: {`);

    const tq = hasTanStackQuery(api.plugins);
    const ns = `${apiName}Types`;

    if (api.apiType === "rest") {
      emitRestTypes(lines, api, ns, tq);
    } else {
      emitGraphQLTypes(lines, api, ns, tq);
    }

    lines.push(`      pathKey(): readonly ['magia', '${apiName}']`);
    lines.push(`    }`);
  }

  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);

  return lines.join("\n");
}

function emitRestTypes(lines: string[], api: GenRestApiInfo, ns: string, tq: boolean): void {
  for (const op of api.operations) {
    const isMut = op.entry.method !== "GET";
    const opId = op.operationName;

    // openapi-typescript uses the operationId as-is in the operations interface
    // We need to find the matching key — check both raw and capitalized
    const hasOp = api.exportedTypes.has(opId);

    // Type references using openapi-typescript's operations interface
    let reqType: string;
    let resType: string;
    let errType: string;

    if (hasOp) {
      reqType = `FlatInput<${ns}.operations[${JSON.stringify(opId)}]>`;
      resType = `SuccessResponse<${ns}.operations[${JSON.stringify(opId)}]["responses"]>`;
      errType = `ErrorResponses<${ns}.operations[${JSON.stringify(opId)}]["responses"]>`;
    } else {
      reqType = "void";
      resType = "void";
      errType = "{}";
    }

    // SSE endpoints get MagiaSSEOperation instead of the normal types
    if (op.entry.sse) {
      lines.push(`      ${opId}: MagiaSSEOperation<${reqType}, ${resType}>`);
      continue;
    }

    if (isMut) {
      let line = `      ${opId}: MagiaMutation<${reqType}, ${resType}, ${errType}>`;
      if (tq) line += `\n        & MagiaTanStackMutation<${reqType}, ${resType}>`;
      lines.push(line);
    } else {
      let line = `      ${opId}: MagiaOperation<${reqType}, ${resType}, ${errType}>`;
      if (tq) line += `\n        & MagiaTanStackQuery<${reqType}, ${resType}>`;
      if (tq && op.entry.pagination)
        line += `\n        & MagiaTanStackInfiniteQuery<${reqType}, ${resType}>`;
      lines.push(line);
    }
  }
}

function emitGraphQLTypes(lines: string[], api: GenGraphQLApiInfo, ns: string, tq: boolean): void {
  for (const op of api.operations) {
    const isMut = op.kind === "mutation";
    const isSub = op.kind === "subscription";
    const capName = capitalize(op.operationName);

    // graphql-codegen generates: GetUserQuery, GetUserQueryVariables
    const queryTypeName = `${capName}Query`;
    const mutationTypeName = `${capName}Mutation`;
    const subscriptionTypeName = `${capName}Subscription`;
    const variablesTypeName = `${capName}QueryVariables`;
    const mutVarsTypeName = `${capName}MutationVariables`;
    const subVarsTypeName = `${capName}SubscriptionVariables`;

    let resType: string;
    let reqType: string;

    if (op.kind === "query") {
      resType = api.exportedTypes.has(queryTypeName) ? `${ns}.${queryTypeName}` : "unknown";
      reqType = api.exportedTypes.has(variablesTypeName) ? `${ns}.${variablesTypeName}` : "void";
    } else if (op.kind === "mutation") {
      resType = api.exportedTypes.has(mutationTypeName) ? `${ns}.${mutationTypeName}` : "unknown";
      reqType = api.exportedTypes.has(mutVarsTypeName) ? `${ns}.${mutVarsTypeName}` : "void";
    } else {
      resType = api.exportedTypes.has(subscriptionTypeName)
        ? `${ns}.${subscriptionTypeName}`
        : "unknown";
      reqType = api.exportedTypes.has(subVarsTypeName) ? `${ns}.${subVarsTypeName}` : "void";
    }

    // GraphQL subscriptions get MagiaSSEOperation
    if (isSub) {
      lines.push(`      ${op.operationName}: MagiaSSEOperation<${reqType}, ${resType}>`);
      continue;
    }

    if (isMut) {
      let line = `      ${op.operationName}: MagiaMutation<${reqType}, ${resType}>`;
      if (tq) line += `\n        & MagiaTanStackMutation<${reqType}, ${resType}>`;
      lines.push(line);
    } else {
      let line = `      ${op.operationName}: MagiaOperation<${reqType}, ${resType}>`;
      if (tq) line += `\n        & MagiaTanStackQuery<${reqType}, ${resType}>`;
      if (tq && op.pagination)
        line += `\n        & MagiaTanStackInfiniteQuery<${reqType}, ${resType}>`;
      lines.push(line);
    }
  }
}
