import type { ExtractedOperation } from './extractor'
import type { MagiaPlugin } from '../types'

/**
 * Generate magia.gen.ts source code from extracted operations.
 * This file lives in the user's src/ directory (gitignored).
 */
export function generateManifestSource(
  apis: Record<string, { operations: ExtractedOperation[]; plugins: MagiaPlugin[] }>,
): string {
  const lines: string[] = []

  lines.push(`// Auto-generated by magia-api — do not edit`)
  lines.push(`import type { Manifest } from 'magia-api'`)
  lines.push(``)
  lines.push(`export const manifest: Manifest = {`)

  for (const [apiName, api] of Object.entries(apis)) {
    lines.push(`  ${JSON.stringify(apiName)}: {`)

    // Plugins
    const pluginsList = api.plugins.map(p => `{ name: ${JSON.stringify(p.name)} }`).join(', ')
    lines.push(`    plugins: [${pluginsList}],`)

    // Operations
    lines.push(`    operations: {`)
    for (const op of api.operations) {
      const params = JSON.stringify(op.entry.params)
      lines.push(`      ${JSON.stringify(op.operationName)}: {`)
      lines.push(`        method: ${JSON.stringify(op.entry.method)},`)
      lines.push(`        path: ${JSON.stringify(op.entry.path)},`)
      lines.push(`        params: ${params},`)
      lines.push(`      },`)
    }
    lines.push(`    },`)
    lines.push(`  },`)
  }

  lines.push(`}`)
  lines.push(``)

  return lines.join('\n')
}
